function aH = add_figure_annotation(figH, aStr)
% aH = add_figure_annotation(figH, aStr)
% adds a text box anootation with string aStr to figure in handle fH
% location will be at bottom left of figure.
% aH = annotation(figH, 'textbox', [0.005 0.00 .1 .05], ...
% 	                'String', aStr, 'FitBoxToText', 'on', ...
% 						 'FontSize', 9, ...
% 						 'LineStyle', 'none', ...
% 						 'VerticalAlignment', 'bottom', ...
% 						 'Interpreter', 'none');

aH = annotation(figH, 'textbox', [0.005 0.00 .1 .05], ...
	                'String', aStr, 'FitBoxToText', 'on', ...
						 'FontSize', 9, ...
						 'LineStyle', 'none', ...
						 'VerticalAlignment', 'bottom', ...
						 'Interpreter', 'none');

